### ISSUE TITLE
An error has occured. Check your logs for clarification.

### ISSUE THREAD

**Issue by shahronak47** [brandonkopp/RPS#1]
After few initial successful attempts. I keep on getting this error message. 

![image](https://user-images.githubusercontent.com/10164875/39660530-e26fb8a6-5073-11e8-9bd0-cc859b46da3b.png)

The error messages appear for a second or so and disappear. Doesn't break the functionality though. Could not find a fixed time when the error messages appear.

**Comment by brandonkopp** [comment]
Thank you Ronak. This was my first ever issue report. I am happy to say that that issue has been solved. The problem was that there was a lag between when the value for the images and the text was changed to NULL and when those elements were cleared from the screen. Sometimes that lag was long enough for the error text to be visible. I fixed it by (1) showing blank images and (2) showing an empty text string "" when the values of the player and computer are NULL.

I also updated the way the app stores data. It no longer stores locally (which Shinyapps can't do anyways). It saves to Google Sheets. That way, the app can continue to learn from all of the players it plays against.

Thanks again for this report.
